version: '3'

services:
  php-fpm:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www
  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./.docker/nginx/sites/:/etc/nginx/sites-available:delegated
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d:delegated
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "BileMo"
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3307:3306"
    volumes:
      - ./database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###< doctrine/doctrine-bundle ###
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - "8081:80"
