version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "BileMo"
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###< doctrine/doctrine-bundle ###
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - "8081:80"
